### ISSUE TITLE
Pixelload doesn't work in Kubuntu 18.04 

### ISSUE THREAD

**Issue by styfrombrest** [rbn42/pixelload#1]
I've installed required dependencies according to the docs:
`sudo apt-get install qml-module-qt-websockets \
    python3-docopt python3-numpy python3-psutil python3-websockets python3-pil `

But widget doesn't work - it's just empty(color scheme is default):
![image](https://user-images.githubusercontent.com/6871536/74648980-fc5e7780-517e-11ea-9e1d-ae6e7111ee6a.png)

KDE Plasma version: 5.12.9
Kubuntu 18.04

**Comment by rbn42** [comment]
I see it in my system too. This error belongs to [the upstream](https://pypi.org/project/psutil/). Hope they can solve it ASAP.
```bash
 ~/git/pixelload/pixelload/backend master > python disk.py 
Traceback (most recent call last):
  File "disk.py", line 19, in <module>
    print(next(start(3)))
  File "disk.py", line 7, in start
    data = psutil.disk_io_counters(perdisk=False)
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 23531 18723 1862205 9367 10550 14296 455716 11521 0 17907 8067 0 0 0 0 1251 3221\n'
```

**Comment by rbn42** [comment]
> giampaolo commented 9 hours ago
> I just released a new version which fixes this issue. 

Upstream solved this issue.
